#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";

const check = process.argv.includes("--check");
const packageJson = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const version = packageJson.version;

if (typeof version !== "string" || version.length === 0) {
  throw new Error("package.json version must be a non-empty string");
}

const target = new URL("../src/version.ts", import.meta.url);
const content = `// This file is generated by scripts/sync-version.mjs. Do not edit by hand.\nexport const EXTENSION_VERSION = ${JSON.stringify(version)};\n`;

if (check) {
  const current = readFileSync(target, "utf8");
  if (current !== content) {
    console.error("src/version.ts is out of sync with package.json. Run `pnpm run sync:version`.");
    process.exit(1);
  }
} else {
  writeFileSync(target, content);
}
